development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name            : "dev.testing321@gmail.com",
  :password             : "HazratMuhammad1",
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name            : "dev.testing321@gmail.com",
  :password             : "HazratMuhammad1",
  :enable_starttls_auto: true